apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: {{ .Values.mlflow.image }}
          command: ["mlflow"]
          args: 
            - "server"
            - "--backend-store-uri"
            - "postgresql://{{ .Values.postgresql.username }}:{{ .Values.postgresql.password }}@postgresql:5432/{{ .Values.postgresql.database }}"
            - "--artifacts-destination"
            - "s3://{{ .Values.minio.bucket }}"
            - "--host"
            - "0.0.0.0" 
            - "--port"
            - "5000"
          ports:
            - containerPort: 5000
          env:
            - name: MLFLOW_TRACKING_URI
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: MLFLOW_TRACKING_URI
            - name: MLFLOW_S3_ENDPOINT_URL
              valueFrom:
                configMapKeyRef:
                  name: mlflow-config
                  key: MLFLOW_S3_ENDPOINT_URL
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: accessKey
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: secretKey