apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  username: {{ .Values.postgresql.username | b64enc }}
  password: {{ .Values.postgresql.password | b64enc }}