apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 10Gi  # Adjust the storage size as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/minio  # Adjust the path as needed