apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  accessKey: {{ .Values.minio.accessKey | b64enc }}
  secretKey: {{ .Values.minio.secretKey | b64enc }}