apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: {{ .Values.model.name }}
  namespace: {{ .Release.Namespace }}
spec:
  predictor:
    serviceAccountName: {{ .Values.model.name }}-sa
    minReplicas: {{ .Values.model.minReplicas }}
    model:
      modelFormat:
        name: sklearn
      storageUri: s3://mlflow-bucket/{{ .Values.model.storageUri }}
      resources:
        requests:
          cpu: "100m"
          memory: "512Mi"
        limits:
          cpu: "1"
          memory: "1Gi"