apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    serving.kserve.io/s3-endpoint: minio.mlflow-ns.svc.cluster.local:9000 # replace with your s3 endpoint
    serving.kserve.io/s3-usehttps: "0" # by default 1, for testing with minio you need to set to 0
type: Opaque
stringData: # use `stringData` for raw credential string or `data` for base64 encoded string
  AWS_ACCESS_KEY_ID: minio
  AWS_SECRET_ACCESS_KEY: minio123
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.model.name }}-sa
  namespace: {{ .Release.Namespace }}
secrets:
  - name: minio-secret
--- 